version: '3.8'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:root@postgres/repository_chat

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: repository_chat
